version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nirvaha-backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/nirvaha
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - nirvaha-network
      

  nirvaha-ui:
    build:
      context: ./nirvaha-ui
      dockerfile: Dockerfile
    container_name: nirvaha-ui
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nirvaha-network

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: nirvaha-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nirvaha-ui/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nirvaha-ui
    networks:
      - nirvaha-network
    profiles:
      - proxy

  mongo:
    image: mongo:8
    container_name: nirvaha-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - nirvaha-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 
    driver: local
  nirvaha-data:
    driver: local


networks:
  nirvaha-network:
    driver: bridge